### ISSUE TITLE
Please add license to this repo

### ISSUE THREAD

**Issue by jasnow** [bparanj/trail#1]
Suggest you add a license file to this repo such as: https://github.com/jasnow/Practice-Git-with-Rails/blob/master/MIT-LICENSE.txt

Other license info at: http://opensource.org/licenses

**Comment by jasnow** [comment]
Other license info at: http://opensource.org/licenses

**Comment by jasnow** [comment]
@bparanj - Is adding a repo license a good idea?

**Comment by bparanj** [comment]
This repo is free to use for any purpose. It's just a sample Rails app illustrating paper trail.

**Comment by jasnow** [comment]
Then a Apache or MIT license would be prefect for it.

**Comment by jasnow** [comment]
http://stackoverflow.com/questions/5521080/can-i-use-the-code-in-a-github-project-which-does-not-have-a-license-specified
